name: Release
on:
  push:
    tags: ["v*"]
jobs:
  release:
    uses: mvslovers/mbt/.github/workflows/release3.yml@feat/v3-release
    permissions:
      contents: write
    with:
      mbt_ref: feat/v3-release
